import assert from 'node:assert/strict';
import fs from 'node:fs';

const dynamics=fs.readFileSync('./app-dynamics-v36.js','utf8');
const calendar=fs.readFileSync('./calendar-autonomous-v35.js','utf8');
const connection=fs.readFileSync('./connection-client.js','utf8');
const config=fs.readFileSync('./config.mjs','utf8');
const sw=fs.readFileSync('./sw.js','utf8');
let checks=0;
const check=(condition,message)=>{checks++;assert.ok(condition,`${checks}. ${message}`)};
check(dynamics.includes("VERSION='3.6.0'"),'versión v36');
check(dynamics.includes('#dynScoreboard'),'marcador compartido');
check(dynamics.includes('#dynAutomation'),'panel de automatizaciones');
check(dynamics.includes('laliga:calendar-updated'),'escucha de actualización de calendario');
check(dynamics.includes("fetch('/api/health'"),'salud de backend automática');
check(dynamics.includes('setInterval(()=>{void health()'), 'health heartbeat');
check(dynamics.includes('visibilitychange'),'reanudar sincronización al volver a la app');
check(dynamics.includes('STALE_MS=90000'),'detección de datos obsoletos');
check(dynamics.includes('REFRESH_MS=15000'),'mismo ciclo de 15 segundos');
check(dynamics.includes('linear-gradient(145deg,var(--dyn-panel),var(--dyn-panel2))'),'estética basada en el calendario');
check(dynamics.includes('.nav button.active'),'navegación con identidad dinámica');
check(dynamics.includes("live.length?'live':''"),'estado live visual');
check(dynamics.includes('m.homeScore')&&dynamics.includes('m.awayScore'),'marcador por resultado');
check(dynamics.includes('EN DIRECTO'),'estado en directo visible');
check(calendar.includes("new CustomEvent('laliga:calendar-updated"),'calendario publica sus resultados');
check(calendar.includes('updatedAt:Date.now()'),'timestamp de actualización');
check(calendar.includes('getState:()=>'),'estado del calendario expuesto de forma segura');
check(connection.indexOf('/app-dynamics-v36.js')<connection.indexOf('/calendar-autonomous-v35.js'),'shell cargado antes que calendario');
check(config.includes("'/app-dynamics-v36.js'"),'asset público');
check(sw.includes("'./app-dynamics-v36.js'"),'asset cacheado en PWA');
check(sw.includes("CACHE_NAME='fm-v307'"),'caché PWA rotada');
check(!/api[_-]?key|bearer\s+[A-Za-z0-9._-]{20,}|x-apisports-key/i.test(dynamics),'sin secretos en frontend');
check(!dynamics.includes("/api/calendar/autonomous"),'sin segunda petición de calendario');
check(dynamics.includes("window.LALIGA_CALENDAR_V35?.refresh?.()"),'reutiliza el refresco oficial al volver');
assert.equal(checks,24,`Se esperaban 24 comprobaciones y hay ${checks}`);
console.log(`APP DYNAMICS v36: ${checks}/${checks} checks passed`);
