import assert from 'node:assert/strict';
import fs from 'node:fs';
const dynamics=fs.readFileSync('./app-dynamics-v37.js','utf8');
const connection=fs.readFileSync('./connection-client.js','utf8');
const config=fs.readFileSync('./config.mjs','utf8');
const sw=fs.readFileSync('./sw.js','utf8');
const pkg=JSON.parse(fs.readFileSync('./package.json','utf8'));
let n=0;const check=(ok,msg)=>{n++;assert.ok(ok,`V37-${String(n).padStart(3,'0')}: ${msg}`)};
check(dynamics.includes("VERSION='3.7.0'"),'version v37');
check(dynamics.includes('#dyn37ops'),'operations panel exists');
check(dynamics.includes('lastCalendarAt')&&dynamics.includes('lastHealthAt'),'last update telemetry');
check(dynamics.includes('nextCycle()')&&dynamics.includes('Próximo ciclo'),'next cycle telemetry');
check(dynamics.includes('consecutiveFailures')&&dynamics.includes('errorCount'),'failure counters');
check(dynamics.includes('RETRY_DELAYS=[5000,15000,30000]'),'bounded retry backoff');
check(dynamics.includes("laliga:layer-error")&&dynamics.includes('scheduleRetry'),'automatic layer-error recovery');
check(dynamics.includes("window.LALIGA_CALENDAR_V35?.refresh"),'reuses calendar refresh controller');
check(!dynamics.includes("fetch('/api/calendar/autonomous"),'does not duplicate calendar API');
check(dynamics.includes('laliga:calendar-updated'),'uses shared calendar event');
check(dynamics.includes('health()')&&dynamics.includes('HEALTH_MS=60000'),'health heartbeat retained');
check(dynamics.includes('STALE_MS=90000'),'stale detection retained');
check(dynamics.includes('visibilitychange'),'resume automation retained');
check(connection.includes("loadInline('/app-dynamics-v37.js','37')"),'connection loads v37');
check(!connection.includes("loadInline('/app-dynamics-v36.js','36')"),'old dynamics loader removed');
check(config.includes("'/app-dynamics-v37.js'"),'v37 public asset');
check(!config.includes("'/app-dynamics-v36.js'"),'v36 public asset removed');
check(sw.includes("CACHE_NAME='fm-v308'"),'cache rotated');
check(sw.includes("'./app-dynamics-v37.js'"),'v37 cached');
check(!sw.includes("'./app-dynamics-v36.js'"),'v36 cache entry removed');
check(pkg.scripts.test.includes('app-dynamics-v37.test.mjs'),'v37 regression in npm test');
console.log(`APP DYNAMICS v37: ${n}/${n} checks passed`);
