(() => {
  'use strict';
  const panelId = 'laligaPasswordLoginV211';
  function ensurePanel(){
    if(document.getElementById(panelId)) return;
    const panel=document.createElement('section'); panel.id=panelId; panel.className='card'; panel.style.cssText='margin:12px 0;border:1px solid #30394d;border-radius:15px;background:#111722;padding:12px;';
    panel.innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start;flex-wrap:wrap"><div><h3 style="margin:0 0 4px">🔐 Conectar cuenta LALIGA</h3><div style="font-size:10px;color:#9aa3b7">Inicio directo contra LALIGA · sesión HttpOnly · solo lectura</div></div><div id="laligaAuthBadgeV211" class="pill">No conectada</div></div><form id="laligaAuthFormV211" style="margin-top:10px"><label style="display:block;font-size:12px;margin-bottom:6px">Correo de LALIGA</label><input id="laligaEmailV211" type="email" autocomplete="username" required maxlength="320" style="width:100%;box-sizing:border-box;margin-bottom:8px"><label style="display:block;font-size:12px;margin-bottom:6px">Contraseña</label><input id="laligaPasswordV211" type="password" autocomplete="current-password" required maxlength="1024" style="width:100%;box-sizing:border-box;margin-bottom:8px"><div style="display:flex;gap:8px;flex-wrap:wrap"><button type="submit" class="primary">Conectar de forma segura</button><button type="button" id="laligaLogoutV211">Cerrar sesión</button></div></form><div id="laligaAuthMsgV211" class="note" style="margin-top:9px">La contraseña se envía una sola vez por HTTPS al backend y no se guarda en el navegador ni en GitHub.</div>`;
    const hero=document.querySelector('.hero'); if(hero?.parentNode) hero.parentNode.insertBefore(panel,hero.nextSibling); else document.querySelector('.app')?.prepend(panel);
    panel.querySelector('form').addEventListener('submit',login); panel.querySelector('#laligaLogoutV211').addEventListener('click',logout);
  }
  function msg(t){const n=document.getElementById('laligaAuthMsgV211');if(n)n.textContent=t}
  function badge(t,c=''){const n=document.getElementById('laligaAuthBadgeV211');if(n){n.className=`pill ${c}`.trim();n.textContent=t}}
  async function session(){const r=await fetch('/api/session',{credentials:'include',cache:'no-store'});return r.json()}
  async function login(e){e.preventDefault();const email=document.getElementById('laligaEmailV211').value.trim(),password=document.getElementById('laligaPasswordV211').value;const button=e.currentTarget.querySelector('button[type="submit"]');button.disabled=true;badge('Conectando…','yellow');msg('Autenticando directamente contra LALIGA…');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',cache:'no-store',body:JSON.stringify({email,password})});const data=await r.json().catch(()=>({}));document.getElementById('laligaPasswordV211').value='';if(!r.ok)throw new Error(data.error||`HTTP_${r.status}`);badge('Conectada','good');msg('Cuenta conectada. Sincronizando tus datos Fantasy…');window.dispatchEvent(new CustomEvent('laliga:authenticated'));window.dispatchEvent(new Event('laliga:sync-now'));}catch(error){badge('No conectada','red');msg(error.message==='LOGIN_RATE_LIMITED'?'Demasiados intentos. Espera unos minutos.':'No se pudo autenticar la cuenta. Comprueba las credenciales o inicia sesión desde LALIGA.')}finally{button.disabled=false}}
  async function logout(){await fetch('/auth/logout',{credentials:'include',cache:'no-store'}).catch(()=>{});badge('No conectada');msg('Sesión cerrada.');window.dispatchEvent(new Event('laliga:logout'))}
  async function boot(){ensurePanel();try{const s=await session();if(s.authenticated){badge('Conectada','good');msg('Sesión LALIGA activa.');window.dispatchEvent(new Event('laliga:authenticated'))}}catch{}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
