(() => {
  'use strict';
  const panelId = 'laligaAuthPanelV212';
  const $ = id => document.getElementById(id);
  function ensurePanel(){
    if($(panelId)) return;
    const panel=document.createElement('section'); panel.id=panelId; panel.className='card';
    panel.style.cssText='margin:10px 0;border:1px solid #30394d;border-radius:15px;background:#111722;padding:12px;';
    panel.innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><div><h3 style="margin:0 0 3px">🔐 Cuenta LALIGA</h3><div id="laligaAuthHintV212" style="font-size:10px;color:#9aa3b7">Conexión oficial · sesión segura · solo lectura</div></div><div id="laligaAuthBadgeV212" class="pill">No conectada</div></div><div id="laligaAuthActionsV212" style="margin-top:10px;display:grid;gap:8px"><button type="button" class="primary" id="laligaSsoV212">Entrar con LALIGA</button><button type="button" id="laligaPasswordToggleV212">Usar correo y contraseña</button></div><form id="laligaAuthFormV212" hidden style="margin-top:9px"><label style="display:block;font-size:12px;margin-bottom:6px">Correo de LALIGA</label><input id="laligaEmailV212" type="email" autocomplete="username" required maxlength="320" style="width:100%;box-sizing:border-box;margin-bottom:8px"><label style="display:block;font-size:12px;margin-bottom:6px">Contraseña</label><input id="laligaPasswordV212" type="password" autocomplete="current-password" required maxlength="1024" style="width:100%;box-sizing:border-box;margin-bottom:8px"><div style="display:flex;gap:8px;flex-wrap:wrap"><button type="submit" class="primary">Conectar</button><button type="button" id="laligaPasswordCancelV212">Cancelar</button></div></form><button type="button" id="laligaLogoutV212" hidden style="margin-top:9px">Cerrar sesión</button><div id="laligaAuthMsgV212" class="note" style="margin-top:9px">El modo recomendado usa el acceso oficial de LALIGA. La contraseña alternativa solo se envía una vez por HTTPS y no se guarda en el navegador ni en GitHub.</div>`;
    const hero=document.querySelector('.hero'); if(hero?.parentNode) hero.parentNode.insertBefore(panel,hero.nextSibling); else document.querySelector('.app')?.prepend(panel);
    $('laligaSsoV212').addEventListener('click',startSso); $('laligaPasswordToggleV212').addEventListener('click',showPasswordForm); $('laligaPasswordCancelV212').addEventListener('click',hidePasswordForm); $('laligaAuthFormV212').addEventListener('submit',login); $('laligaLogoutV212').addEventListener('click',logout);
  }
  function msg(t){const n=$('laligaAuthMsgV212');if(n)n.textContent=t}
  function badge(t,c=''){const n=$('laligaAuthBadgeV212');if(n){n.className=`pill ${c}`.trim();n.textContent=t}}
  function showPasswordForm(){const f=$('laligaAuthFormV212');if(f)f.hidden=false;$('laligaPasswordToggleV212').hidden=true;msg('Acceso alternativo: usa las credenciales de tu cuenta LALIGA.')}
  function hidePasswordForm(){const f=$('laligaAuthFormV212');if(f)f.hidden=true;$('laligaPasswordToggleV212').hidden=false;const p=$('laligaPasswordV212');if(p)p.value='';msg('El acceso oficial de LALIGA es la opción recomendada.')}
  async function session(){const r=await fetch('/api/session',{credentials:'include',cache:'no-store'});return r.json()}
  async function authStatus(){const r=await fetch('/api/auth/status',{credentials:'include',cache:'no-store'});return r.ok?r.json():null}
  function startSso(){badge('Redirigiendo…','yellow');msg('Abriendo el acceso oficial de LALIGA…');window.location.assign('/auth/start?platform=web')}
  async function login(e){e.preventDefault();const email=$('laligaEmailV212').value.trim(),password=$('laligaPasswordV212').value,button=e.currentTarget.querySelector('button[type="submit"]');button.disabled=true;badge('Conectando…','yellow');msg('Autenticando directamente contra LALIGA…');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',cache:'no-store',body:JSON.stringify({email,password})});const data=await r.json().catch(()=>({}));$('laligaPasswordV212').value='';if(!r.ok)throw new Error(data.error||`HTTP_${r.status}`);badge('Conectada','good');hidePasswordForm();msg('Cuenta conectada. Sincronizando tus datos Fantasy…');window.dispatchEvent(new CustomEvent('laliga:authenticated'));window.dispatchEvent(new Event('laliga:sync-now'));}catch(error){badge('No conectada','red');msg(error.message==='LOGIN_RATE_LIMITED'?'Demasiados intentos. Espera unos minutos.':'No se pudo autenticar la cuenta. Comprueba las credenciales o usa el acceso oficial de LALIGA.')}finally{button.disabled=false}}
  async function logout(){await fetch('/auth/logout',{credentials:'include',cache:'no-store'}).catch(()=>{});badge('No conectada');$('laligaLogoutV212').hidden=true;$('laligaSsoV212').hidden=false;$('laligaPasswordToggleV212').hidden=false;msg('Sesión cerrada.');window.dispatchEvent(new Event('laliga:logout'))}
  function connected(){badge('Conectada','good');$('laligaSsoV212').hidden=true;$('laligaPasswordToggleV212').hidden=true;$('laligaLogoutV212').hidden=false;msg('Sesión LALIGA activa. Sincronizando datos reales en modo lectura…');window.dispatchEvent(new Event('laliga:authenticated'))}
  async function boot(){ensurePanel();try{const [s,a]=await Promise.all([session(),authStatus()]);if(s.authenticated)connected();else if(a&&!a.configured)msg('Acceso oficial no configurado en este entorno. Puedes usar el acceso alternativo con correo y contraseña.')}catch{}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
