import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createPlayerHistory } from './brain-history-v28.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'laliga-history-'));
const h=createPlayerHistory({dir,maxPerPlayer:4});
const players=[{id:10,name:'Jugador Uno',teamName:'Equipo A',weekPoints:8,minutes:90,starts:1},{id:11,name:'Jugador Dos',teamName:'Equipo B',weekPoints:2,minutes:45,starts:0}];
let r=h.observe(players,{week:1,source:'official'});assert.equal(r.players,2);assert.equal(r.newPlayers,2);
r=h.observe([{...players[0],weekPoints:12},{...players[1],weekPoints:4}],{week:2,source:'official'});assert.equal(r.players,2);
let p=h.profile('10');assert.equal(p.found,true);assert.equal(p.labeledSamples,2);assert.equal(p.recentAveragePoints,10);assert.equal(p.formTrend,0);
const reloaded=createPlayerHistory({dir,maxPerPlayer:4});assert.equal(reloaded.profile('10').recentAveragePoints,10);
reloaded.observe(Array.from({length:8},(_,i)=>({id:10,name:'Jugador Uno',teamName:'Equipo A',weekPoints:i})),{week:3,source:'official'});assert.ok(reloaded.profile('10').samples<=4);
console.log('Calendar/player history v28: 100% passed');
