import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createPlayerHistory } from './brain-history-v28.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'laliga-history-finality-'));
const h=createPlayerHistory({dir,maxPerPlayer:8});
const player={id:7,name:'Jugador',teamName:'Equipo',weekPoints:9,minutes:90,starts:1};
h.observe([player],{week:10,source:'official',final:false});
assert.equal(h.profile('7').labeledSamples,0);
h.observe([player],{week:10,source:'official',final:true});
assert.equal(h.profile('7').labeledSamples,1);
assert.equal(h.profile('7').averagePoints,9);
console.log('Brain history finality v34: 3/3 passed');
