import assert from 'node:assert/strict';
import fs from 'node:fs';
const pkg=JSON.parse(fs.readFileSync('./package.json','utf8'));
assert.equal(pkg.scripts.start.includes('--import ./brain-history-hook-v28.mjs'),true);
assert.equal(pkg.scripts.start.includes('--import ./brain-reliability-hook-v29.mjs'),true);
assert.equal((pkg.scripts.start.match(/brain-history-hook-v28\.mjs/g)||[]).length,1);
assert.equal((pkg.scripts.start.match(/brain-reliability-hook-v29\.mjs/g)||[]).length,1);
const history=fs.readFileSync('./brain-history-hook-v28.mjs','utf8');
const reliability=fs.readFileSync('./brain-reliability-hook-v29.mjs','utf8');
assert.ok(history.includes('Symbol.for')||history.includes('globalThis'));
assert.ok(reliability.includes('Symbol.for')||reliability.includes('globalThis'));
console.log('Brain hook safety v33: 8/8 passed');
