import assert from 'node:assert/strict';
import fs from 'node:fs';
const cal34=fs.readFileSync('./calendar-autonomous-v34.js','utf8');
const cal35=fs.readFileSync('./calendar-autonomous-v35.js','utf8');
const conn=fs.readFileSync('./connection-client.js','utf8');
const detail=fs.readFileSync('./match-detail-ui-v31.js','utf8');
const sw=fs.readFileSync('./sw.js','utf8');
assert.ok(cal34.includes('/api/calendar/autonomous'),'legacy v34 uses autonomous live endpoint');
assert.ok(/loadInline\('\/calendar-autonomous-v35\.js','35'\)/.test(conn),'connection loads calendar v35');
assert.ok(cal35.includes('inferCurrentMatchday'),'v35 infers current jornada from context');
assert.ok(cal35.includes('localDay(now)'),'v35 uses Madrid local day');
assert.ok(cal35.includes('liveRows.length'),'v35 prioritizes live matches');
assert.ok(cal35.includes('Jornada anterior')&&cal35.includes('Jornada siguiente'),'v35 has jornada navigation');
assert.ok(cal35.includes('var(--red')&&cal35.includes('var(--panel')&&cal35.includes('var(--line'),'v35 reuses application theme variables');
assert.ok(cal35.includes('data-match-id')&&cal35.includes('openDetail(m)'),'v35 opens detail on match click');
assert.ok(detail.includes('/api/futbolfantasy/data'),'detail uses normalized fantasy data endpoint');
assert.ok(detail.includes("String(m.id??'')===String(match.id??'')"),'detail resolves by match id before fallbacks');
assert.ok(sw.includes('./calendar-autonomous-v35.js'),'service worker caches v35');
console.log('CALENDAR UI v35: 10/10 assertions passed');
