import assert from 'node:assert/strict';
import fs from 'node:fs';
const cal=fs.readFileSync('./calendar-autonomous-v34.js','utf8');
const conn=fs.readFileSync('./connection-client.js','utf8');
const detail=fs.readFileSync('./match-detail-ui-v31.js','utf8');
const sw=fs.readFileSync('./sw.js','utf8');
assert.ok(/loadInline\('\/calendar-autonomous-v34\.js','34'\)/.test(conn),'connection loads calendar v34');
assert.ok(cal.includes('/api/calendar/autonomous'),'calendar uses autonomous live endpoint');
assert.ok(cal.includes('EN DIRECTO'),'calendar exposes live state');
assert.ok(cal.includes('Jornada anterior')&&cal.includes('Jornada siguiente'),'calendar has jornada navigation');
assert.ok(cal.includes('matchday'),'calendar filters/groups by jornada');
assert.ok(cal.includes('data-match-id')&&cal.includes('openDetail(m)'),'calendar opens detail on match click');
assert.ok(detail.includes('/api/futbolfantasy/data'),'detail uses normalized fantasy data endpoint');
assert.ok(detail.includes("String(m.id??'')===String(match.id??'')"),'detail resolves by match id before fallbacks');
assert.ok(sw.includes('./calendar-autonomous-v34.js'),'service worker caches calendar v34');
console.log('CALENDAR UI v34: 9/9 assertions passed');
