import assert from 'node:assert/strict';
import fs from 'node:fs';
const cal=fs.readFileSync('./calendar-autonomous-v30.js','utf8');
const detail=fs.readFileSync('./match-detail-ui-v31.js','utf8');
assert.ok(cal.includes('data-matchday')||cal.includes('matchday'),'calendar groups by matchday');
assert.ok(cal.includes('previous')&&cal.includes('next'),'calendar supports jornada navigation');
assert.ok(cal.includes('EN DIRECTO'),'calendar exposes live state');
assert.ok(cal.includes('/api/calendar/autonomous'),'calendar uses autonomous live endpoint');
assert.ok(cal.includes('openDetail(match)'),'calendar opens match detail');
assert.ok(detail.includes('/api/futbolfantasy/data'),'detail uses normalized fantasy endpoint');
assert.ok(detail.includes('lineups?.home')&&detail.includes('lineups?.away'),'detail supports both lineups');
assert.ok(detail.includes('No se ha encontrado una referencia específica'),'detail refuses fabricated data');
console.log('CALENDAR UI v34: 8/8 structural assertions passed');
