import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createCultivos, CULTIVOS_VERSION } from './cultivos-v1.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cultivos-'));const c=createCultivos({dir});
assert.equal(CULTIVOS_VERSION,'1.1.0');assert.equal(c.summary().version,'1.1.0');
c.observe({source:'test',outcome:'success',dimensions:{prediction:2,data:1},detail:'ok'});assert.equal(c.summary().dimensions.prediction,2);assert.equal(c.summary().dimensions.data,1);
c.observe({source:'test',outcome:'failure',dimensions:{automation:-2},detail:'fail'});assert.equal(c.summary().dimensions.automation,-2);
c.syncFromBrain({accuracy:70,reliability:{reliability:.75,dataQuality:.9}});c.syncFromAutomation({eventCount:5,recentErrors:[]});c.syncFromEvidence({captureCount:1,recordingCount:1});assert.equal(c.summary().cycles,5);assert.equal(c.summary().recentEvents.length,5);
const persisted=createCultivos({dir}).summary();assert.equal(persisted.cycles,5);assert.equal(persisted.recentEvents.length,5);assert.ok(fs.existsSync(c.file));
console.log('CULTIVOS v1.1: 8/8 checks passed');
