import assert from 'node:assert/strict';
import fs from 'node:fs';
const detail=fs.readFileSync('./match-detail-ui-v31.js','utf8');
const connection=fs.readFileSync('./connection-client.js','utf8');
const calendar=fs.readFileSync('./calendar-autonomous-v30.js','utf8');
const sw=fs.readFileSync('./sw.js','utf8');
assert.ok(connection.includes("load('/match-detail-ui-v31.js'"),'match detail layer loaded');
assert.ok(calendar.includes('LALIGA_MATCH_DETAIL.open'),'calendar opens match detail on click');
assert.ok(detail.includes("/api/futbolfantasy/data"),'uses existing FutbolFantasy endpoint');
assert.ok(detail.includes('lineups')&&detail.includes('lineups?.home')&&detail.includes('lineups?.away'),'supports normalized home/away lineup payloads');
assert.ok(detail.includes('predictedPoints')&&detail.includes('possiblePoints')&&detail.includes('points'),'supports possible-points fields');
assert.ok(detail.includes('No se ha encontrado una referencia específica'),'does not fabricate unavailable match references');
assert.ok(detail.includes('Las posibles puntuaciones son estimaciones'),'estimates are labelled');
assert.ok(sw.includes('./match-detail-ui-v31.js'),'PWA caches match detail layer');
console.log('MATCH DETAIL v31: 8/8 checks passed');
