import { fetchFutbolFantasy } from './calendar-service-v29.mjs';
import { detectFixtureConflicts } from './fixture-conflicts-v1.mjs';
function providerError(name,status,message){return Object.assign(new Error(message||`${name}_FAILED`),{provider:name,status:status||502});}
async function getJson(name,url,headers={}){let response;try{response=await fetch(url,{method:'GET',headers:{Accept:'application/json','User-Agent':'LALIGA-Fantasy-Manager/3.0.0',...headers},cache:'no-store',signal:AbortSignal.timeout(12000)});}catch(error){throw providerError(name,502,error?.name==='TimeoutError'?`${name}_TIMEOUT`:`${name}_NETWORK_ERROR`)}const text=await response.text();let data={};try{data=JSON.parse(text)}catch{throw providerError(name,response.status||502,`${name}_INVALID_JSON`)}if(!response.ok){const msg=data?.message||data?.errors?.join?.(', ')||'';throw providerError(name,response.status,`${name}_${response.status}${msg?`: ${msg}`:''}`)}return data;}
export function daysWindow(days){const safe=Math.min(Math.max(Number(days)||30,1),90),now=new Date(),from=now.toISOString().slice(0,10),to=new Date(now.getTime()+safe*86400000).toISOString().slice(0,10);return{from,to};}
const scoreValue=v=>{const n=Number(v);return Number.isInteger(n)&&n>=0&&n<=99?n:null};
const officialScore=(home,away)=>({homeScore:scoreValue(home),awayScore:scoreValue(away)});
export function normalizeFootballData(data){return(Array.isArray(data?.matches)?data.matches:[]).map(m=>{const score=m?.score?.fullTime||m?.score?.current||{};return{provider:'football-data.org',id:String(m?.id??''),competitionId:String(m?.competition?.code??''),utcDate:m?.utcDate||null,home:m?.homeTeam?.name||null,away:m?.awayTeam?.name||null,status:m?.status||null,matchday:Number.isFinite(Number(m?.matchday))?Number(m?.matchday):null,round:m?.stage||null,...officialScore(score.home,score.away),homeTeamId:m?.homeTeam?.id??null,awayTeamId:m?.awayTeam?.id??null,raw:m};});}
export function normalizeApiFootball(data){return(Array.isArray(data?.response)?data.response:[]).map(m=>({provider:'api-football',id:String(m?.fixture?.id??''),competitionId:String(m?.league?.id??''),utcDate:m?.fixture?.date||null,home:m?.teams?.home?.name||null,away:m?.teams?.away?.name||null,status:m?.fixture?.status?.short||null,matchday:null,round:m?.league?.round||null,...officialScore(m?.goals?.home,m?.goals?.away),homeTeamId:m?.teams?.home?.id??null,awayTeamId:m?.teams?.away?.id??null,raw:m}));}
export function normalizeSportmonks(data){return(Array.isArray(data?.data)?data.data:[]).map(m=>{const ps=Array.isArray(m?.participants)?m.participants:[],home=ps.find(x=>x?.meta?.location==='home')||ps[0],away=ps.find(x=>x?.meta?.location==='away')||ps[1],scores=m?.scores||{};return{provider:'sportmonks',id:String(m?.id??''),competitionId:String(m?.league_id??''),utcDate:m?.starting_at||null,home:home?.name||null,away:away?.name||null,status:m?.state?.short_name||m?.state?.name||null,matchday:null,round:m?.round?.name||null,...officialScore(scores?.home?.current??scores?.home?.display,scores?.away?.current??scores?.away?.display),homeTeamId:home?.id??null,awayTeamId:away?.id??null,raw:m};});}
function cleanTeamName(n){return String(n||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|cf|sd|ud|real|club|de|del|la|cd)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ')}
export function fixtureKey(m){const d=m?.utcDate?new Date(m.utcDate):null;const day=Number.isFinite(d?.getTime())?d.toISOString().slice(0,10):'';return[day,cleanTeamName(m?.home),cleanTeamName(m?.away)].join('|');}
export function providerStatus(config){return{footballData:{configured:Boolean(config.footballDataToken),competition:config.footballDataCompetition},sportmonks:{configured:Boolean(config.sportmonksToken&&config.sportmonksLeagueId),leagueConfigured:Boolean(config.sportmonksLeagueId)},apiFootball:{configured:Boolean(config.apiFootballKey),leagueId:config.apiFootballLeagueId,season:config.apiFootballSeason},opta:{configured:Boolean(config.optaToken&&config.optaBaseUrl&&config.optaFixturesPath)},futbolFantasy:{configured:Boolean(config.futbolFantasyUrl),url:config.futbolFantasyUrl,readOnly:true,role:'contraste público'}}}
export async function fetchApiFootballFixtures(config,from,to){if(!config.apiFootballKey)throw providerError('API_FOOTBALL',503,'API_FOOTBALL_NOT_CONFIGURED');const q=new URLSearchParams({league:config.apiFootballLeagueId,season:config.apiFootballSeason,from,to}),data=await getJson('API_FOOTBALL',`${config.apiFootballBase}/fixtures?${q}`,{'x-apisports-key':config.apiFootballKey});if(Array.isArray(data?.errors)&&data.errors.length)throw providerError('API_FOOTBALL',502,`API_FOOTBALL_UPSTREAM: ${data.errors.join(', ')}`);return normalizeApiFootball(data);}
export async function fetchSportmonksFixtures(config,from,to){if(!config.sportmonksToken||!config.sportmonksLeagueId)throw providerError('SPORTMONKS',503,'SPORTMONKS_NOT_CONFIGURED');const q=new URLSearchParams({api_token:config.sportmonksToken,include:'participants;round;league;scores',filters:`fixtureLeagues:${config.sportmonksLeagueId}`,per_page:'50'}),data=await getJson('SPORTMONKS',`${config.sportmonksBase}/fixtures/between/${encodeURIComponent(from)}/${encodeURIComponent(to)}?${q}`);return normalizeSportmonks(data);}
export async function fetchOptaFixtures(config){if(!config.optaToken||!config.optaBaseUrl||!config.optaFixturesPath)throw providerError('OPTA',503,'OPTA_NOT_CONFIGURED');const url=new URL(config.optaFixturesPath,`${config.optaBaseUrl}/`);if(config.optaCompetitionId&&!url.searchParams.has('competitionId'))url.searchParams.set('competitionId',config.optaCompetitionId);const data=await getJson('OPTA',url.toString(),{Authorization:`Bearer ${config.optaToken}`,'X-API-Key':config.optaToken});const response=Array.isArray(data?.response)?data.response:Array.isArray(data?.data)?data.data:[];return response.map(m=>{const score=m?.score||m?.scores||{};return{provider:'opta',id:String(m?.id??m?.matchId??''),competitionId:String(m?.competitionId??config.optaCompetitionId??''),utcDate:m?.utcDate||m?.date||m?.startDate||null,home:m?.home||m?.homeTeam?.name||m?.homeTeam||null,away:m?.away||m?.awayTeam?.name||m?.awayTeam||null,status:m?.status||null,matchday:Number.isFinite(Number(m?.matchday))?Number(m.matchday):null,round:m?.round||null,...officialScore(score?.home??score?.homeScore,score?.away??score?.awayScore),raw:m};});}
const providerRank=new Map([['api-football',4],['football-data.org',3],['sportmonks',2],['opta',1],['futbolFantasy',0]]);
function mergeFixture(existing,candidate,name){const a=existing||{id:candidate.id,utcDate:candidate.utcDate,home:candidate.home,away:candidate.away,homeTeam:candidate.homeTeamId?{id:candidate.homeTeamId,name:candidate.home}:null,awayTeam:candidate.awayTeamId?{id:candidate.awayTeamId,name:candidate.away}:null,status:candidate.status,matchday:candidate.matchday,officialMatchday:candidate.matchday,round:candidate.round||null,homeScore:candidate.homeScore??null,awayScore:candidate.awayScore??null,source:name,sources:[name]};if(!a.sources.includes(name))a.sources.push(name);if(providerRank.get(name)>providerRank.get(a.source||'futbolFantasy')){a.source=name;a.id=candidate.id||a.id;a.utcDate=candidate.utcDate||a.utcDate;a.status=candidate.status||a.status;if(candidate.homeScore!=null)a.homeScore=candidate.homeScore;if(candidate.awayScore!=null)a.awayScore=candidate.awayScore}else{if(a.homeScore==null&&candidate.homeScore!=null)a.homeScore=candidate.homeScore;if(a.awayScore==null&&candidate.awayScore!=null)a.awayScore=candidate.awayScore;if(candidate.status&&['FT','FINISHED','FINAL','ENDED','COMPLETED'].includes(String(candidate.status).toUpperCase()))a.status=candidate.status}if(a.matchday==null&&candidate.matchday!=null)a.matchday=candidate.matchday;if(!a.round&&candidate.round)a.round=candidate.round;return a;}
export async function fetchMultiProviderFixtures(config){const {from,to}=daysWindow(config.footballDataDays);const jobs={'api-football':()=>config.apiFootballKey?fetchApiFootballFixtures(config,from,to):Promise.reject(providerError('API_FOOTBALL',503,'API_FOOTBALL_NOT_CONFIGURED')),'football-data.org':()=>config.footballDataToken?getJson('FOOTBALL_DATA',`${config.footballDataBase}/competitions/${encodeURIComponent(config.footballDataCompetition)}/matches?dateFrom=${from}&dateTo=${to}`,{'X-Auth-Token':config.footballDataToken}).then(normalizeFootballData):Promise.reject(providerError('FOOTBALL_DATA',503,'FOOTBALL_DATA_NOT_CONFIGURED')),sportmonks:()=>fetchSportmonksFixtures(config,from,to),opta:()=>fetchOptaFixtures(config),futbolFantasy:()=>fetchFutbolFantasy(config)};const entries=await Promise.all(Object.entries(jobs).map(async([name,job])=>{try{const raw=await job();const matches=Array.isArray(raw)?raw:Array.isArray(raw?.matches)?raw.matches:[];return[name,{ok:true,matches}]}catch(error){return[name,{ok:false,error:error.message,status:error.status||502}]}}));const providers=Object.fromEntries(entries);const conflicts=detectFixtureConflicts(providers);const priority=['api-football','football-data.org','sportmonks','opta','futbolFantasy'];const mergedMap=new Map;for(const name of priority){const r=providers[name];if(!r?.ok)continue;for(const m of r.matches){const k=fixtureKey(m),old=mergedMap.get(k),merged=mergeFixture(old,m,name);mergedMap.set(k,merged)}}const merged=[...mergedMap.values()].sort((a,b)=>new Date(a.utcDate||0)-new Date(b.utcDate||0));return{from,to,primaryProvider:priority.find(n=>providers[n]?.ok)||null,providers,counts:Object.fromEntries(Object.entries(providers).map(([n,r])=>[n,r.ok?r.matches.length:0])),conflicts,conflictCount:conflicts.length,merged};}
