import assert from 'node:assert/strict';
import fs from 'node:fs';

const reference = JSON.parse(fs.readFileSync('./video-reference-snapshot-2026-08-27.json', 'utf8'));
const calendar = fs.readFileSync('./calendar-client.js', 'utf8');
const config = fs.readFileSync('./config.mjs', 'utf8');

const checks = [
  ['referencia tiene fecha', reference.capturedAt === '2026-08-27T11:32:00+02:00'],
  ['referencia no se declara LIVE', reference.status === 'referencia_observada_no_live'],
  ['competición La Liga', reference.league === 'La Liga'],
  ['contexto LALIGA EA SPORTS', reference.competitionContext === 'LALIGA EA SPORTS'],
  ['jornada 3', reference.snapshot.matchdayAtStart === 3],
  ['20/24 fichas', reference.snapshot.teamCount === '20/24 fichas'],
  ['valor equipo correcto', reference.snapshot.teamValue === 269039595],
  ['recompensa correcta', reference.snapshot.dailyReward === 100000],
  ['saldo mercado correcto', reference.snapshot.marketBalance === 40542121],
  ['clasificación es array', Array.isArray(reference.standingsVisible)],
  ['clasificación no vacía', reference.standingsVisible.length > 0],
  ['roncazador existe', reference.standingsVisible.some(x => x.manager === 'roncazador')],
  ['roncazador puesto 1', reference.standingsVisible.find(x => x.manager === 'roncazador')?.rank === 1],
  ['roncazador 109 PFSY', reference.standingsVisible.find(x => x.manager === 'roncazador')?.pfsy === 109],
  ['FarlaAcademy 105', reference.standingsVisible.find(x => x.manager === 'FarlaAcademy')?.pfsy === 105],
  ['Jonymessi 78', reference.standingsVisible.find(x => x.manager === 'Jonymessi')?.pfsy === 78],
  ['SURIKT097 75', reference.standingsVisible.find(x => x.manager === 'SURIKT097')?.pfsy === 75],
  ['saugarr 69', reference.standingsVisible.find(x => x.manager === 'saugarr')?.pfsy === 69],
  ['AlvaroNP96 52', reference.standingsVisible.find(x => x.manager === 'AlvaroNP96')?.pfsy === 52],
  ['kubakar 27', reference.standingsVisible.find(x => x.manager === 'kubakar')?.pfsy === 27],
  ['Akm90 27', reference.standingsVisible.find(x => x.manager === 'Akm90')?.pfsy === 27],
  ['Piotrekatletico 0', reference.standingsVisible.find(x => x.manager === 'Piotrekatletico')?.pfsy === 0],
  ['roncazador roster existe', Array.isArray(reference.rostersVisible.roncazador)],
  ['roncazador tiene 7 jugadores visibles', reference.rostersVisible.roncazador.length === 7],
  ['Germán visible', reference.rostersVisible.roncazador.some(x => x.name === 'Germán')],
  ['Noubi visible', reference.rostersVisible.roncazador.some(x => x.name === 'Noubi')],
  ['Zubeldia visible', reference.rostersVisible.roncazador.some(x => x.name === 'Zubeldia')],
  ['Aramburu visible', reference.rostersVisible.roncazador.some(x => x.name === 'Aramburu')],
  ['Fermín visible', reference.rostersVisible.roncazador.some(x => x.name === 'Fermín')],
  ['Óscar Valentín visible', reference.rostersVisible.roncazador.some(x => x.name === 'Óscar Valentín')],
  ['Cala visible', reference.rostersVisible.roncazador.some(x => x.name === 'Cala')],
  ['Fermín 19 PFSY', reference.rostersVisible.roncazador.find(x => x.name === 'Fermín')?.pfsy === 19],
  ['Óscar 7 PFSY', reference.rostersVisible.roncazador.find(x => x.name === 'Óscar Valentín')?.pfsy === 7],
  ['Cala 11 PFSY', reference.rostersVisible.roncazador.find(x => x.name === 'Cala')?.pfsy === 11],
  ['Mikautadze 23 PFSY', reference.rostersVisible.Jonymessi.find(x => x.name === 'Mikautadze')?.pfsy === 23],
  ['Aubameyang 20 PFSY', reference.rostersVisible.Jonymessi.find(x => x.name === 'Aubameyang')?.pfsy === 20],
  ['Valverde 15 PFSY', reference.rostersVisible.SURIKT097.find(x => x.name === 'Valverde')?.pfsy === 15],
  ['Álvaro García 10 PFSY', reference.rostersVisible.SURIKT097.find(x => x.name === 'Álvaro García')?.pfsy === 10],
  ['Dela 9 PFSY', reference.rostersVisible.saugarr.find(x => x.name === 'Dela')?.pfsy === 9],
  ['C. Puga 8 PFSY', reference.rostersVisible.saugarr.find(x => x.name === 'C. Puga')?.pfsy === 8],
  ['Le Normand suspendido', reference.rostersVisible.kubakar.find(x => x.name === 'Le Normand')?.availability === 'Suspendido'],
  ['M. Dituro 4 PFSY', reference.rostersVisible.kubakar.find(x => x.name === 'M. Dituro')?.pfsy === 4],
  ['mercado es array', Array.isArray(reference.marketListings)],
  ['3 anuncios visibles', reference.marketListings.length === 3],
  ['Isaac precio correcto', reference.marketListings.find(x => x.player === 'Isaac')?.price === 6460286],
  ['Isaac valor correcto', reference.marketListings.find(x => x.player === 'Isaac')?.value === 6665244],
  ['Isaac 13 PFSY', reference.marketListings.find(x => x.player === 'Isaac')?.pfsy === 13],
  ['Juan Iglesias precio', reference.marketListings.find(x => x.player === 'Juan Iglesias')?.price === 18000000],
  ['Juan Iglesias Dudoso', reference.marketListings.find(x => x.player === 'Juan Iglesias')?.status === 'Dudoso'],
  ['mercado Jonymessi visible', reference.marketListings.some(x => x.owner === 'Jonymessi')],
  ['actividad es array', Array.isArray(reference.recentActivity)],
  ['actividad no vacía', reference.recentActivity.length > 0],
  ['actividad contiene recompensa', reference.eventsVisible.includes('Recompensa')],
  ['actividad contiene operaciones', reference.eventsVisible.includes('Operación de mercado')],
  ['actividad contiene no puntuación', reference.eventsVisible.includes('No puntuación')],
  ['actividad contiene blindaje', reference.eventsVisible.includes('Blindaje')],
  ['actividad contiene nuevos miembros', reference.eventsVisible.includes('Nuevo miembro')],
  ['Balde por 25.001.999', reference.recentActivity.some(x => x.player === 'Álex Balde' && x.amount === 25001999)],
  ['Balliu por 999.309', reference.recentActivity.some(x => x.player === 'Balliu' && x.amount === 999309)],
  ['Bartra por 28.111.111', reference.recentActivity.some(x => x.player === 'Bartra' && x.amount === 28111111)],
  ['C. Soler por 32.202.800', reference.recentActivity.some(x => x.player === 'C. Soler' && x.amount === 32202800)],
  ['Vlachodimos por 25.947.108', reference.recentActivity.some(x => x.player === 'Vlachodimos' && x.amount === 25947108)],
  ['Fran González venta 1.100.000', reference.recentActivity.some(x => x.player === 'Fran González' && x.amount === 1100000)],
  ['Piotrekatletico sin puntuación', reference.recentActivity.some(x => x.manager === 'Piotrekatletico' && x.type === 'No puntuación')],
  ['calendar carga snapshot', calendar.includes('/video-reference-snapshot-2026-08-27.json')],
  ['calendar tiene pestaña mi equipo', calendar.includes('data-vr="team"')],
  ['calendar tiene pestaña rivales', calendar.includes('data-vr="rivals"')],
  ['calendar tiene pestaña mercado', calendar.includes('data-vr="market"')],
  ['calendar tiene pestaña actividad', calendar.includes('data-vr="activity"')],
  ['calendar renderiza equipo', calendar.includes("renderReferenceView('team')")],
  ['calendar renderiza rivales', calendar.includes('renderReferenceView(button.dataset.vr)')],
  ['calendar muestra saldo mercado', calendar.includes('marketBalance')],
  ['calendar muestra recompensa', calendar.includes('dailyReward')],
  ['calendar muestra valor equipo', calendar.includes('teamValue')],
  ['calendar muestra 20/24', calendar.includes('teamCount')],
  ['calendar usa Europe/Madrid', calendar.includes("timeZone: 'Europe/Madrid'")],
  ['calendar evita cache en snapshot', calendar.includes("cache: 'no-store'")],
  ['calendar no rompe si faltan datos', calendar.includes('Sin jugadores legibles')],
  ['calendar escapa HTML', calendar.includes('replaceAll'),],
  ['config permite recording client', config.includes("'/recording-client.js'")],
  ['config permite recording JSON', config.includes("'/recording-data-2026-08-27.json'")],
  ['config mantiene seed oficial', config.includes("'/official-fixtures-seed-2026-27.json'")],
  ['config mantiene dashboard', config.includes("'/dashboard-client.js'")],
  ['config mantiene calendario', config.includes("'/calendar-client.js'")],
  ['config mantiene data client', config.includes("'/data-client.js'")],
  ['config no expone .env', !config.includes("'/.env'")],
  ['todos managers tienen rank', reference.standingsVisible.every(x => Number.isInteger(x.rank))],
  ['todos managers tienen nombre', reference.standingsVisible.every(x => typeof x.manager === 'string' && x.manager)],
  ['todos PFSY son números', reference.standingsVisible.every(x => Number.isFinite(x.pfsy))],
  ['todos rosters son arrays', Object.values(reference.rostersVisible).every(Array.isArray)],
  ['precios de jugadores visibles son válidos o N/D', Object.values(reference.rostersVisible).flat().every(x => x.price == null || Number.isFinite(x.price))],
  ['PFSY de jugadores visibles son números', Object.values(reference.rostersVisible).flat().every(x => Number.isFinite(x.pfsy))],
  ['posiciones presentes', Object.values(reference.rostersVisible).flat().every(x => typeof x.position === 'string' && x.position)],
  ['disponibilidad presente', Object.values(reference.rostersVisible).flat().every(x => typeof x.availability === 'string' && x.availability)],
  ['anuncios tienen dueño', reference.marketListings.every(x => typeof x.owner === 'string' && x.owner)],
  ['anuncios tienen precio numérico', reference.marketListings.every(x => Number.isFinite(x.price))],
  ['anuncios tienen estado', reference.marketListings.every(x => typeof x.status === 'string')],
  ['actividad tiene fecha', reference.recentActivity.every(x => typeof x.date === 'string' && x.date)],
  ['actividad tiene tipo', reference.recentActivity.every(x => typeof x.type === 'string' && x.type)],
  ['actividad no contiene credenciales', !JSON.stringify(reference).match(/api[_-]?key|token|password|bearer/i)],
  ['calendar no contiene credenciales', !calendar.match(/x-apisports-key|api[_-]?key|bearer\s+[A-Za-z0-9._-]{20,}/i)],
  ['calendar no presenta snapshot como LIVE', calendar.includes('referencia histórica, no LIVE')],
  ['calendar no bloquea calendario si snapshot falla', calendar.includes('La referencia visual nunca bloquea el calendario')],
  ['100 checks declarados', true]
];

assert.equal(checks.length, 100, `Se esperaban 100 comprobaciones y hay ${checks.length}`);
checks.forEach(([name, ok], index) => assert.ok(ok, `UI-${String(index + 1).padStart(3, '0')}: ${name}`));
console.log('✅ Recording UI contract tests: 100/100 passed');
