import assert from 'node:assert/strict';
import fs from 'node:fs';
const files = p => fs.readFileSync(p,'utf8');
const recording=files('recording-client.js'), dataClient=files('data-client.js'), dashboard=files('dashboard-client.js'), connection=files('connection-client.js'), calendar=files('calendar-client.js'), config=files('config.mjs'), index=files('index.html'), sw=files('sw.js'), pkg=JSON.parse(files('package.json'));
const checks=[];
const check=(name,ok)=>checks.push([name,Boolean(ok)]);
check('package v2.13',pkg.version==='2.13.0');
check('recording client existe',recording.length>0);
check('data client existe',dataClient.length>0);
check('calendar v2.13 activo',calendar.includes("const V='2.13.0'"));
check('fuente única LALIGA oficial',calendar.includes("OFF='LALIGA oficial'"));
check('calendario oficial autenticado',calendar.includes('/api/fantasy/fixtures?week='));
check('semilla oficial',calendar.includes('official-fixtures-seed-2026-27.json'));
check('estado en directo',calendar.includes('EN DIRECTO'));
check('marcador local',calendar.includes('homeScore')&&calendar.includes('awayScore'));
check('deduplicación',calendar.includes('new Map'));
check('botones grandes',calendar.includes('min-height:64px'));
check('interfaz única',calendar.includes('officialFantasyApp'));
check('dashboard heredado desactivado',dashboard.includes('FANTASY_LEGACY_DASHBOARD_DISABLED'));
check('conexión heredada desactivada',connection.includes('LALIGA_LEGACY_CONNECTION_DISABLED'));
check('calendario no usa API-Football',!calendar.includes('api-football'));
check('calendario no usa football-data',!calendar.includes('football-data'));
check('calendario no usa Sportmonks',!calendar.includes('sportmonks'));
check('calendario no usa Opta',!calendar.includes('opta'));
check('index responsive',index.includes('@media(max-width:560px)'));
check('index táctil',index.includes('overflow:auto'));
check('config calendario público',config.includes("'/calendar-client.js'"));
check('config semilla pública',config.includes("'/official-fixtures-seed-2026-27.json'"));
check('service worker v2.13',sw.includes("CACHE_NAME = 'fm-v213'"));
check('service worker cachea calendar',sw.includes("'./calendar-client.js'"));
const secret=/(?:x-apisports-key|YOUR_API_KEY|Bearer\s+[A-Za-z0-9._-]{20,}|apiFootballKey\s*[:=]\s*['"][A-Za-z0-9._-]{20,}['"])/i;
check('calendar sin secretos',!secret.test(calendar));
check('data client sin secretos',!secret.test(dataClient));
check('recording sin secretos',!secret.test(recording));
check('config sin .env público',!config.includes("'/.env'"));
assert.equal(checks.length,29);
for(const [i,[name,ok]] of checks.entries())assert.ok(ok,`V32-${String(i+1).padStart(3,'0')}: ${name}`);
console.log('✅ V32: 29/29 comprobaciones superadas');
