import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

import { VERSION, readConfig, oidcConfigured, publicStaticPath } from './config.mjs';
import { providerStatus, fetchApiFootballFixtures, fetchSportmonksFixtures, fetchMultiProviderFixtures } from './providers.mjs';
import { fetchTeams, fetchPlayers, fetchStandings, fetchInjuries } from './realdata.mjs';

const config = readConfig();
const sessions = new Map();
const loginAttempts = new Map();
const STATIC_DIR = path.resolve(process.env.FRONTEND_DIR || process.cwd());
const READ_ROUTES = new Set(['profile', 'leagues', 'league', 'squad', 'budget', 'market', 'fixtures', 'players', 'stats', 'rivals', 'standings', 'week']);
const SESSION_PENDING_TTL = 15 * 60 * 1000;
const SESSION_ACTIVE_TTL = 30 * 24 * 60 * 60 * 1000;
const LOGIN_WINDOW_MS = 10 * 60 * 1000;
const LOGIN_MAX_ATTEMPTS = 8;

function sendJson(res, status, body){
  const headers = {'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Pragma':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY'};
  if (config.allowOrigin) { headers['Access-Control-Allow-Origin']=config.allowOrigin; headers['Access-Control-Allow-Credentials']='true'; }
  res.writeHead(status, headers); res.end(JSON.stringify(body));
}
function parseCookies(req){ const out={}; for(const part of String(req.headers.cookie||'').split(';')){ const i=part.indexOf('='); if(i<0) continue; const k=part.slice(0,i).trim(), v=part.slice(i+1).trim(); if(!k) continue; try{out[k]=decodeURIComponent(v)}catch{out[k]=v} } return out; }
function getSession(req){ const id=parseCookies(req)[config.sessionCookieName]; if(!id) return null; const s=sessions.get(id); if(!s) return null; const ttl=s.accessToken?SESSION_ACTIVE_TTL:SESSION_PENDING_TTL; if(Date.now()-s.createdAt>ttl){sessions.delete(id);return null} return s; }
function cleanSessions(){ const now=Date.now(); for(const [id,s] of sessions){ const ttl=s.accessToken?SESSION_ACTIVE_TTL:SESSION_PENDING_TTL; if(now-s.createdAt>ttl) sessions.delete(id); } for(const [ip,a] of loginAttempts){ if(now-a.startedAt>LOGIN_WINDOW_MS) loginAttempts.delete(ip); } }
setInterval(cleanSessions,5*60*1000).unref();
function staticContentType(file){ return {'index.html':'text/html; charset=utf-8','manifest.json':'application/manifest+json; charset=utf-8','sw.js':'text/javascript; charset=utf-8','dashboard-client.js':'text/javascript; charset=utf-8','calendar-client.js':'text/javascript; charset=utf-8','data-client.js':'text/javascript; charset=utf-8','connection-client.js':'text/javascript; charset=utf-8','auth-client.js':'text/javascript; charset=utf-8','official-fixtures-seed-2026-27.json':'application/json; charset=utf-8'}[file]||'application/octet-stream'; }
function serveStatic(res,pathname){ if(!publicStaticPath(pathname)) return false; const file=pathname==='/'?'index.html':pathname.slice(1), full=path.resolve(STATIC_DIR,file); if(!full.startsWith(STATIC_DIR+path.sep)||!fs.existsSync(full)||!fs.statSync(full).isFile()) return false; let content=fs.readFileSync(full,'utf8'); if(file==='index.html'&&content.includes('</body>')){ for(const src of ['/dashboard-client.js','/calendar-client.js','/data-client.js','/connection-client.js','/auth-client.js']) if(!content.includes(src)) content=content.replace('</body>',`  <script src="${src}" defer></script>\n</body>`); } res.writeHead(200,{'Content-Type':staticContentType(file),'Cache-Control':file==='index.html'?'no-cache':'public, max-age=3600','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY'}); res.end(content); return true; }
function arrayData(v){if(Array.isArray(v))return v;if(Array.isArray(v?.data))return v.data;if(Array.isArray(v?.items))return v.items;if(Array.isArray(v?.content))return v.content;return[]}
function objectData(v){if(v?.data&&typeof v.data==='object'&&!Array.isArray(v.data))return v.data;if(v&&typeof v==='object'&&!Array.isArray(v))return v;return null}
function oidcStatus(){const required=['LALIGA_AUTHORIZE_URL','LALIGA_OAUTH_CLIENT_ID','LALIGA_REDIRECT_URI'];return{configured:oidcConfigured(config),passwordLogin:true,missing:required.filter(k=>!process.env[k]),hasAuthorizeUrl:Boolean(config.laligaAuthorizeUrl),hasClientId:Boolean(config.laligaOAuthClientId),hasRedirectUri:Boolean(config.laligaRedirectUri),policy:config.laligaSigninPolicy}}
function jwtPayload(token){try{const p=String(token).split('.')[1];if(!p)return null;return JSON.parse(Buffer.from(p,'base64url').toString('utf8'))}catch{return null}}
function validAccessToken(token){const p=jwtPayload(token);if(!p||typeof p!=='object')return false;const now=Math.floor(Date.now()/1000);const aud=Array.isArray(p.aud)?p.aud:[p.aud];return aud.includes(config.laligaPasswordClientId)&&p.iss===config.laligaExpectedIssuer&&Number(p.exp)>now+30}
function loginAllowed(ip){const now=Date.now();const a=loginAttempts.get(ip);if(!a||now-a.startedAt>LOGIN_WINDOW_MS){loginAttempts.set(ip,{startedAt:now,count:1});return true} if(a.count>=LOGIN_MAX_ATTEMPTS)return false;a.count++;return true}
async function refresh(session){if(!session?.refreshToken||!config.laligaOAuthClientId)return false;const tokenUrl=`${config.laligaTokenUrl}?p=${encodeURIComponent(config.laligaSigninPolicy)}`,body=new URLSearchParams({grant_type:'refresh_token',refresh_token:session.refreshToken,client_id:config.laligaOAuthClientId,scope:`openid ${config.laligaOAuthClientId} offline_access`});const response=await fetch(tokenUrl,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body,cache:'no-store'}),data=await response.json().catch(()=>({}));if(!response.ok||(!data.access_token&&!data.id_token))return false;session.accessToken=data.access_token||data.id_token;session.refreshToken=data.refresh_token||session.refreshToken;session.expiresAt=Date.now()+Number(data.expires_in||86400)*1000;session.createdAt=Date.now();return true}
async function upstream(endpoint,session,attempt=0){if(!session?.accessToken)throw Object.assign(new Error('NO_SESSION'),{status:401});if(session.expiresAt&&Date.now()>session.expiresAt-120000)await refresh(session).catch(()=>false);const response=await fetch(config.laligaApiBaseUrl+endpoint,{headers:{Accept:'application/json','x-lang':'es',Authorization:`Bearer ${session.accessToken}`,'User-Agent':`LALIGA-Fantasy-Manager/${VERSION}-read-only`},cache:'no-store'});const text=await response.text();if(response.status===401&&attempt===0&&session.refreshToken&&await refresh(session))return upstream(endpoint,session,1);if(!response.ok)throw Object.assign(new Error(`UPSTREAM_${response.status}`),{status:response.status});try{return JSON.parse(text)}catch{return{raw:text.slice(0,2000)}}}
function fantasyPath(key,url){const c=encodeURIComponent(config.laligaCompetitionId),w=encodeURIComponent(url.searchParams.get('week')||'1');switch(key){case'profile':return'/v4/user/me?x-lang=es';case'leagues':return`/v1/competition/${c}/leagues?x-lang=es`;case'week':return`/v1/competition/${c}/week/current?x-lang=es`;case'players':return`/v1/competition/${c}/players?x-lang=es`;case'fixtures':return`/v1/competition/${c}/calendar?weekNumber=${w}&x-lang=es`;case'league':return`/v1/competition/${c}/leagues/${encodeURIComponent(url.searchParams.get('id')||'')}/standing?x-lang=es`;case'standings':return`/v1/competition/${c}/leagues/${encodeURIComponent(url.searchParams.get('id')||'')}/standing/${w}?x-lang=es`;case'market':return`/v1/competition/${c}/league/${encodeURIComponent(url.searchParams.get('id')||'')}/market?x-lang=es`;case'squad':return`/v1/competition/${c}/teams/${encodeURIComponent(url.searchParams.get('teamId')||'')}?x-lang=es`;case'budget':return`/v1/competition/${c}/teams/${encodeURIComponent(url.searchParams.get('teamId')||'')}/money?x-lang=es`;case'stats':return`/stats/v1/competition/${c}/stats/week/${w}?x-lang=es`;case'rivals':return`/v1/competition/${c}/leagues/${encodeURIComponent(url.searchParams.get('id')||'')}/standing?x-lang=es`;default:return null}}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS'){const h={};if(config.allowOrigin){h['Access-Control-Allow-Origin']=config.allowOrigin;h['Access-Control-Allow-Credentials']='true';h['Access-Control-Allow-Methods']='GET,POST,OPTIONS';h['Access-Control-Allow-Headers']='Content-Type'}res.writeHead(204,h);return res.end()}
if(url.pathname==='/api/health'&&req.method==='GET')return sendJson(res,200,{ok:true,readOnly:true,competition:config.laligaCompetitionId,version:VERSION,providers:{laligaOAuth:oidcConfigured(config),laligaPasswordLogin:true,footballData:Boolean(config.footballDataToken),...providerStatus(config)}});
if(url.pathname==='/api/session'&&req.method==='GET')return sendJson(res,200,{authenticated:Boolean(getSession(req)),readOnly:true});
if(url.pathname==='/api/auth/status'&&req.method==='GET')return sendJson(res,200,oidcStatus());
if(url.pathname==='/api/providers/status'&&req.method==='GET')return sendJson(res,200,providerStatus(config));
if(url.pathname==='/api/auth/login'&&req.method==='POST'){
 const ip=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim();
 if(!loginAllowed(ip))return sendJson(res,429,{error:'LOGIN_RATE_LIMITED'});
 const chunks=[];let bytes=0;for await(const chunk of req){bytes+=chunk.length;if(bytes>8192)return sendJson(res,413,{error:'REQUEST_TOO_LARGE'});chunks.push(chunk)}
 let body;try{body=JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{return sendJson(res,400,{error:'INVALID_JSON'})}
 const email=typeof body?.email==='string'?body.email.trim():'';const password=typeof body?.password==='string'?body.password:'';
 if(!email||email.length>320||!password||password.length>1024)return sendJson(res,400,{error:'INVALID_CREDENTIALS'});
 try{
   const tokenUrl=`${config.laligaTokenUrl}?p=${encodeURIComponent('B2C_1A_ResourceOwnerv2')}`;
   const tokenResponse=await fetch(tokenUrl,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'password',client_id:config.laligaPasswordClientId,scope:`openid ${config.laligaPasswordClientId} offline_access`,redirect_uri:config.laligaPasswordRedirectUri,username:email,password,response_type:'id_token'}),cache:'no-store'});
   const token=await tokenResponse.json().catch(()=>({}));
   if(!tokenResponse.ok)return sendJson(res,tokenResponse.status===429?429:401,{error:'AUTHENTICATION_FAILED'});
   const accessToken=typeof token.access_token==='string'?token.access_token:'';
   if(!validAccessToken(accessToken))return sendJson(res,502,{error:'INVALID_PROVIDER_TOKEN'});
   const sessionId=crypto.randomUUID();sessions.set(sessionId,{createdAt:Date.now(),accessToken,refreshToken:typeof token.refresh_token==='string'?token.refresh_token:null,expiresAt:Date.now()+Number(token.expires_in||86400)*1000,authMethod:'laliga-password'});
   return sendJsonWithCookie(res,200,{authenticated:true,authMethod:'laliga-password',expiresAt:sessions.get(sessionId).expiresAt},cookieHeader(sessionId,2592000));
 }catch{return sendJson(res,502,{error:'AUTHENTICATION_PROVIDER_UNAVAILABLE'})}
}
if(url.pathname==='/auth/start'&&req.method==='GET'){if(!oidcConfigured(config))return sendJson(res,501,{error:'OIDC_NOT_CONFIGURED',message:'Faltan parámetros OIDC oficiales.'});const state=crypto.randomBytes(32).toString('base64url'),verifier=crypto.randomBytes(32).toString('base64url'),challenge=crypto.createHash('sha256').update(verifier).digest('base64url'),sessionId=crypto.randomUUID();sessions.set(sessionId,{createdAt:Date.now(),state,verifier,platform:url.searchParams.get('platform')==='ios'?'ios':'web'});const query=new URLSearchParams({p:config.laligaSigninPolicy,client_id:config.laligaOAuthClientId,response_type:'code',redirect_uri:config.laligaRedirectUri,scope:`openid ${config.laligaOAuthClientId} offline_access`,code_challenge:challenge,code_challenge_method:'S256',state,nonce:state});res.writeHead(302,{Location:`${config.laligaAuthorizeUrl}?${query.toString()}`,'Set-Cookie':cookieHeader(sessionId,900)});return res.end()}
if(url.pathname==='/auth/callback'&&req.method==='GET'){const sessionId=parseCookies(req)[config.sessionCookieName],pending=sessionId?sessions.get(sessionId):null,code=url.searchParams.get('code'),returnedState=url.searchParams.get('state');if(!pending||!code||returnedState!==pending.state)return sendJson(res,400,{error:'INVALID_OIDC_CALLBACK'});const tokenUrl=`${config.laligaTokenUrl}?p=${encodeURIComponent(config.laligaSigninPolicy)}`,body=new URLSearchParams({grant_type:'authorization_code',client_id:config.laligaOAuthClientId,code,redirect_uri:config.laligaRedirectUri,code_verifier:pending.verifier,scope:`openid ${config.laligaOAuthClientId} offline_access`}),tokenResponse=await fetch(tokenUrl,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body,cache:'no-store'}),token=await tokenResponse.json().catch(()=>({}));if(!tokenResponse.ok||(!token.access_token&&!token.id_token))return sendJson(res,502,{error:'OIDC_TOKEN_EXCHANGE_FAILED'});sessions.set(sessionId,{createdAt:Date.now(),accessToken:token.access_token||token.id_token,refreshToken:token.refresh_token,expiresAt:Date.now()+Number(token.expires_in||86400)*1000});const location=pending.platform==='ios'?config.iosSuccessRedirect:config.frontendUrl;res.writeHead(302,{Location:location,'Set-Cookie':cookieHeader(sessionId,2592000)});return res.end()}
if(url.pathname==='/auth/logout'){const sessionId=parseCookies(req)[config.sessionCookieName];if(sessionId)sessions.delete(sessionId);res.writeHead(302,{Location:config.frontendUrl,'Set-Cookie':cookieHeader('',0)});return res.end()}
if(url.pathname==='/api/fantasy/dashboard'){if(req.method!=='GET')return sendJson(res,405,{error:'GET_ONLY'});const session=getSession(req);if(!session)return sendJson(res,401,{error:'AUTH_REQUIRED'});const output={version:VERSION,readOnly:true,competition:config.laligaCompetitionId,errors:[]};const [profileResult,leaguesResult,weekResult]=await Promise.allSettled([upstream('/v4/user/me?x-lang=es',session),upstream(`/v1/competition/${encodeURIComponent(config.laligaCompetitionId)}/leagues?x-lang=es`,session),upstream(`/v1/competition/${encodeURIComponent(config.laligaCompetitionId)}/week/current?x-lang=es`,session)]);output.profile=profileResult.status==='fulfilled'?objectData(profileResult.value)||{}:{};output.leagues=leaguesResult.status==='fulfilled'?arrayData(leaguesResult.value):[];output.week=weekResult.status==='fulfilled'?objectData(weekResult.value)||weekResult.value:{};if(profileResult.status==='rejected')output.errors.push('profile');if(leaguesResult.status==='rejected')output.errors.push('leagues');if(weekResult.status==='rejected')output.errors.push('week');const league=output.leagues[0],leagueId=league?.id||league?.leagueId;if(leagueId){const competition=encodeURIComponent(config.laligaCompetitionId),encodedLeague=encodeURIComponent(leagueId);const [standingResult,marketResult]=await Promise.allSettled([upstream(`/v1/competition/${competition}/leagues/${encodedLeague}/standing?x-lang=es`,session),upstream(`/v1/competition/${competition}/league/${encodedLeague}/market?x-lang=es`,session)]);output.leagueId=leagueId;output.standing=standingResult.status==='fulfilled'?standingResult.value:null;output.market=marketResult.status==='fulfilled'?marketResult.value:null;if(standingResult.status==='rejected')output.errors.push('standing');if(marketResult.status==='rejected')output.errors.push('market');const rows=arrayData(output.standing),profile=objectData(output.profile)||{},user=profile.username||profile.email||profile.name,mine=rows.find(item=>item?.username===user||item?.managerName===user||item?.manager?.username===user||item?.userId===profile?.id),teamId=mine?.teamId||mine?.team?.id||profile?.teamId||profile?.managerId;if(teamId){const encodedTeam=encodeURIComponent(teamId);const [teamResult,budgetResult]=await Promise.allSettled([upstream(`/v1/competition/${competition}/teams/${encodedTeam}?x-lang=es`,session),upstream(`/v1/competition/${competition}/teams/${encodedTeam}/money?x-lang=es`,session)]);output.team=teamResult.status==='fulfilled'?teamResult.value:null;output.budget=budgetResult.status==='fulfilled'?budgetResult.value:null;output.teamId=teamId;if(teamResult.status==='rejected')output.errors.push('team');if(budgetResult.status==='rejected')output.errors.push('budget')}}}return sendJson(res,200,output)}
if(url.pathname.startsWith('/api/fantasy/')){if(req.method!=='GET')return sendJson(res,405,{error:'READ_ONLY'});const session=getSession(req);if(!session)return sendJson(res,401,{error:'AUTH_REQUIRED'});const key=url.pathname.split('/').filter(Boolean)[2]||'';if(!READ_ROUTES.has(key))return sendJson(res,404,{error:'ROUTE_NOT_ALLOWLISTED'});const endpoint=fantasyPath(key,url);if(!endpoint)return sendJson(res,400,{error:'MISSING_PARAMETER'});try{return sendJson(res,200,await upstream(endpoint,session))}catch(error){return sendJson(res,error.status===401?401:502,{error:'UPSTREAM_READ_FAILED',status:error.status||502})}}
if(req.method==='GET'&&serveStatic(res,url.pathname))return;return sendJson(res,404,{error:'NOT_FOUND'})}catch(error){console.error('SERVER_ERROR',error);return sendJson(res,error.status||500,{error:error.message||'INTERNAL_SERVER_ERROR'})}});
function sendJsonWithCookie(res,status,body,cookie){const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Pragma':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','Set-Cookie':cookie};if(config.allowOrigin){headers['Access-Control-Allow-Origin']=config.allowOrigin;headers['Access-Control-Allow-Credentials']='true'}res.writeHead(status,headers);res.end(JSON.stringify(body))}
function cookieHeader(id,maxAge){const secure=config.secureCookie?'Secure; ':'';return `${config.sessionCookieName}=${encodeURIComponent(id)}; HttpOnly; SameSite=Strict; ${secure}Path=/; Max-Age=${maxAge}`}
server.listen(config.port,config.host,()=>console.log(`Fantasy Manager backend on ${config.host}:${config.port}`));