(()=>{'use strict';
const T=['Athletic Club','Atlético de Madrid','CA Osasuna','Celta','Deportivo Alavés','Elche CF','FC Barcelona','Getafe CF','Levante UD','Málaga CF','R. Racing Club','Rayo Vallecano','RC Deportivo','RCD Espanyol de Barcelona','Real Betis','Real Madrid','Real Sociedad','Sevilla FC','Valencia CF','Villarreal CF'];
const N=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const A=v=>Array.isArray(v)?v:Array.isArray(v?.data)?v.data:Array.isArray(v?.items)?v.items:Array.isArray(v?.content)?v.content:[];
const L=(v,k)=>Array.isArray(v?.[k])?v[k]:A(v);
const E=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const f=(...v)=>v.find(x=>x!=null&&String(x).trim()!=='');
const S={tab:'resumen',teams:[],table:[],players:[],injuries:[],fixtures:[],pages:1,err:[],source:'',loading:false};
const TECH_SCHEDULED=new Set(['TIMED','SCHEDULED','NS','TBD','PENDING','PENDIENTE']);
const TECH_FINAL=new Set(['FT','FINISHED','FINAL','FINALIZADO','COMPLETED']);
const TECH_LIVE=new Set(['LIVE','IN_PLAY','INPLAY','1H','2H','HT','ET','P','EN DIRECTO']);
const TECH_BLOCKED=new Set(['POSTPONED','CANCELLED','CANCELED','APLAZADO','CANCELADO']);
function rawStatus(v){return String(typeof v==='object'?f(v?.status,v?.state,v?.type,v?.code):v??'').trim().toUpperCase()}
function fixtureStatus(v){const s=rawStatus(v);if(TECH_LIVE.has(s))return'EN DIRECTO';if(TECH_FINAL.has(s))return'FINALIZADO';if(TECH_BLOCKED.has(s))return s==='POSTPONED'||s==='APLAZADO'?'APLAZADO':'CANCELADO';if(TECH_SCHEDULED.has(s))return'PRÓXIMO';if(!s)return'ESTADO NO DISPONIBLE';return'ESTADO NO DISPONIBLE'}
function fixtureDate(v){const raw=f(v?.utcDate,v?.date,v?.kickoff,v?.startDate,v?.startTime);if(!raw)return'Sin fecha';const d=new Date(raw);if(Number.isNaN(d.getTime()))return'Sin fecha';return new Intl.DateTimeFormat('es-ES',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Madrid'}).format(d).replaceAll('.','')}
function css(){if(document.getElementById('tv5'))return;const s=document.createElement('style');s.id='tv5';s.textContent=`#teamsDataV5{margin:10px 0 18px}.tv5{background:#0d131b;color:#e7edf5;border:1px solid #263141;border-radius:16px;overflow:hidden}.tv5 *{box-sizing:border-box}.tv5head{padding:14px;border-bottom:1px solid #263141}.tv5title{font-size:18px;font-weight:950}.tv5sub{font-size:7px;color:#8490a1;margin-top:4px}.tv5state{float:right;margin-top:-22px;padding:5px 8px;border-radius:99px;font-size:7px;font-weight:900;background:#132219;border:1px solid #2f684d;color:#6ee7a8}.tv5state.warn{background:#282318;border-color:#665527;color:#ffd166}.tv5tabs{display:flex;gap:5px;margin-top:12px;overflow:auto}.tv5tabs button{border:1px solid #293546;background:#141c26;color:#aeb8c7;border-radius:9px;padding:8px 11px;font-size:8px;font-weight:900}.tv5tabs button.on{background:#e9edf4;color:#101721}.tv5body{padding:10px}.tv5grid{display:grid;grid-template-columns:1.2fr .8fr;gap:8px}.card{background:#101721;border:1px solid #263141;border-radius:11px;overflow:hidden;margin-bottom:8px}.card h3{margin:0;padding:9px 10px;border-bottom:1px solid #263141;font-size:8px}.match{display:grid;grid-template-columns:64px 1fr auto;gap:8px;padding:8px 10px;border-top:1px solid #263141;font-size:7px;align-items:center}.match:first-of-type{border-top:0}.when,.muted{color:#7f8b9c;font-size:6px}.team{font-weight:900}.score{font-weight:950;text-align:right}.status{display:block;margin-top:2px;font-size:6px;font-weight:900;color:#78aaff}.status.live{color:#2bd888}.status.final{color:#b9c3d2}.status.blocked{color:#ffd166}.status.unknown{color:#8f9aae}.table{overflow:auto}.table table{width:100%;border-collapse:collapse;min-width:560px}.table th,.table td,.players th,.players td{padding:7px 8px;border-bottom:1px solid #263141;text-align:left;font-size:7px}.table th,.players th{font-size:6px;color:#7f8b9c;text-transform:uppercase}.club{display:flex;align-items:center;gap:7px;min-width:150px}.club img,.club i{width:24px;height:24px;border-radius:50%;background:#1a2430;border:1px solid #334052;display:grid;place-items:center;font-style:normal;font-size:7px;flex:0 0 24px}.club img{object-fit:contain;padding:3px}.tools{padding:8px}.tools input{width:100%;background:#0b1118;color:#e7edf5;border:1px solid #2a3647;border-radius:8px;padding:8px;font-size:8px}.inj{display:grid;grid-template-columns:auto 1fr auto;gap:8px;padding:8px 10px;border-top:1px solid #263141;font-size:7px}.inj:first-child{border-top:0}.note{padding:8px 10px;border-top:1px solid #263141;color:#7f8b9c;font-size:6px}.empty{padding:16px 10px;text-align:center;color:#7f8b9c;font-size:8px}@media(max-width:740px){.tv5grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function mount(){css();document.getElementById('dataCenterV1')?.classList.add('td-hidden');document.getElementById('teamsDataV4')?.classList.add('td-hidden');let r=document.getElementById('teamsDataV5');if(r)return r;r=document.createElement('section');r.id='teamsDataV5';r.innerHTML=`<div class="tv5"><header class="tv5head"><span id="tv5state" class="tv5state">Cargando</span><div class="tv5title">LALIGA · Datos</div><div class="tv5sub">Resumen primero. Clasificación, jugadores, bajas y calendario quedan separados.</div><nav class="tv5tabs">${['resumen','equipos','jugadores','lesiones','calendario'].map(x=>`<button data-tab="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</nav></header><main class="tv5body"><div id="tv5err"></div><div id="tv5view"></div></main><div class="note">Los números proceden de datos cargados; los 20 clubes son únicamente respaldo de identidad.</div></div>`;document.querySelector('.app')?.prepend(r);r.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;render()});return r}
async function get(u){const r=await fetch(u,{credentials:'include',cache:'no-store'}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{throw Error('JSON')};if(!r.ok)throw Error(d?.error||`HTTP_${r.status}`);return d}
function teams(raw){return L(raw,'teams').map(x=>({name:x.name,key:N(x.name),logo:x.logo})).filter(x=>x.name)}
function table(raw){return L(raw,'standings').map(x=>({rank:num(f(x.rank,x.position)),name:f(x.team,x.teamName,x.name),key:N(f(x.team,x.teamName,x.name)),points:num(f(x.points,x.totalPoints)),played:num(f(x.played,x.matchesPlayed)),wins:num(f(x.wins,x.win)),draws:num(f(x.draws,x.draw)),losses:num(f(x.losses,x.lose)),gf:num(f(x.goalsFor,x.gf)),ga:num(f(x.goalsAgainst,x.ga)),gd:num(f(x.goalDiff,x.gd))})).filter(x=>x.name)}
function players(raw){return L(raw,'players').map(x=>({name:x.name,team:f(x.team,x.teamName),pos:f(x.position,'—'),rating:num(x.rating),goals:num(x.goals),assists:num(x.assists),minutes:num(f(x.minutes,x.appearances))})).filter(x=>x.name)}
function injuries(raw){return L(raw,'injuries').map(x=>({player:f(x.player,x.name),team:f(x.team,x.teamName),reason:f(x.reason,x.type,'Sin detalle'),date:x.date})).filter(x=>x.player)}
function fixtures(raw){const a=[...(raw?.merged||[]),...(raw?.matches||[]),...(raw?.fixtures||[])],seen=new Set();return a.map(x=>({date:f(x.utcDate,x.date,x.kickoff,x.startDate,x.startTime),home:f(x.home,x.homeTeam?.name),away:f(x.away,x.awayTeam?.name),status:f(x.status,'Estado no disponible'),matchday:num(f(x.matchday,x.officialMatchday)),hs:num(x.homeScore??x.goals?.home),as:num(x.awayScore??x.goals?.away),source:f(x.source,'')})).filter(x=>{const k=`${x.date}|${x.home}|${x.away}`;if(!x.date||!x.home||!x.away||seen.has(k))return false;seen.add(k);return true})}
function fixtureTime(x){const d=x.date?new Date(x.date):null;return d&&!Number.isNaN(d.getTime())?d.getTime():null}
function next(){return S.fixtures.filter(x=>{const t=fixtureTime(x),st=fixtureStatus(x.status);return t!=null&&t>=Date.now()&&st!=='FINALIZADO'&&!['APLAZADO','CANCELADO'].includes(st)}).sort((a,b)=>fixtureTime(a)-fixtureTime(b))}
function recent(){return S.fixtures.filter(x=>{const t=fixtureTime(x),st=fixtureStatus(x.status);return t!=null&&t<Date.now()&&(st==='FINALIZADO'||st==='EN DIRECTO')}).sort((a,b)=>fixtureTime(b)-fixtureTime(a))}
function club(t){return `<div class="club">${t.logo?`<img src="${E(t.logo)}" alt="" loading="lazy">`:`<i>${E(String(t.name||'').slice(0,2).toUpperCase())}</i>`}<b>${E(t.name)}</b></div>`}
function tr(t){return `<tr><td><b>${t.rank??'—'}</b></td><td>${club(t)}</td><td>${t.points??'—'}</td><td>${t.played??'—'}</td><td>${t.wins??'—'}</td><td>${t.draws??'—'}</td><td>${t.losses??'—'}</td><td>${t.gf??'—'}</td><td>${t.ga??'—'}</td><td>${t.gd??'—'}</td></tr>`}
function statusClass(st){return st==='EN DIRECTO'?'live':st==='FINALIZADO'?'final':['APLAZADO','CANCELADO'].includes(st)?'blocked':'unknown'}
function match(x){const st=fixtureStatus(x.status),hasScore=x.hs!=null||x.as!=null,score=hasScore?`${x.hs??'—'}–${x.as??'—'}`:'';return `<div class="match"><span class="when">${fixtureDate(x)}</span><span><b class="team">${E(x.home)} · ${E(x.away)}</b><span class="status ${statusClass(st)}">${E(st)}</span><span class="muted">${x.matchday?`J${x.matchday}`:'Calendario'}</span></span>${score?`<b class="score">${E(score)}</b>`:`<b class="score">${E(st)}</b>`}</div>`}
function summary(ts){return `<div class="tv5grid"><section class="card"><h3>Próximos partidos</h3>${next().slice(0,5).map(match).join('')||'<div class="empty">Sin próximos partidos reales.</div>'}</section><section class="card"><h3>Clasificación · top 5</h3><div class="table"><table><thead><tr><th>#</th><th>Equipo</th><th>Pts</th><th>PJ</th><th>DG</th></tr></thead><tbody>${ts.filter(x=>x.rank).slice(0,5).map(t=>`<tr><td><b>${t.rank}</b></td><td>${club(t)}</td><td>${t.points??'—'}</td><td>${t.played??'—'}</td><td>${t.gd??'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Sin clasificación real.</td></tr>'}</tbody></table></div><div class="note">20 equipos completos en «Equipos».</div></section></div><section class="card"><h3>Últimos resultados</h3>${recent().slice(0,4).map(match).join('')||'<div class="empty">Sin resultados reales.</div>'}</section>`}
function teamsView(ts){return `<section class="card"><h3>Clasificación completa · 20 clubes</h3><div class="tools"><input id="tv5s" placeholder="Buscar equipo…" aria-label="Buscar equipo"></div><div class="table"><table><thead><tr><th>#</th><th>Equipo</th><th>Pts</th><th>PJ</th><th>G</th><th>E</th><th>P</th><th>GF</th><th>GC</th><th>DG</th></tr></thead><tbody>${ts.map(tr).join('')}</tbody></table></div></section>`}
function playersRows(p){return p.map(x=>`<tr><td>${E(x.name)}</td><td>${E(x.team||'—')}</td><td>${E(x.pos)}</td><td>${x.rating??'—'}</td><td>${x.goals??'—'}</td><td>${x.assists??'—'}</td><td>${x.minutes??'—'}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Sin jugadores reales.</td></tr>'}
function playersView(){const p=S.players.slice().sort((a,b)=>(b.rating??-1)-(a.rating??-1)||(b.goals??0)-(a.goals??0)).slice(0,40);return `<section class="card"><h3>Jugadores · top 40</h3><div class="tools"><input id="tv5ps" placeholder="Buscar jugador o equipo…" aria-label="Buscar jugador"></div><div class="players table"><table><thead><tr><th>Jugador</th><th>Equipo</th><th>Pos.</th><th>Val.</th><th>G</th><th>A</th><th>Min.</th></tr></thead><tbody id="tv5pt">${playersRows(p)}</tbody></table></div><div class="note">${S.players.length} jugadores cargados en segundo plano.</div></section>`}
function injuriesView(){return `<section class="card"><h3>Lesiones y bajas</h3>${S.injuries.map(x=>`<div class="inj"><b>●</b><span><b>${E(x.player)}</b><br><span class="muted">${E(x.team||'Equipo no disponible')} · ${E(x.reason)}</span></span><span class="muted">${x.date?fixtureDate({date:x.date}):''}</span></div>`).join('')||'<div class="empty">Sin bajas reales.</div>'}</section>`}
function calendarView(){return `<div class="tv5grid"><section class="card"><h3>Próximos 10</h3>${next().slice(0,10).map(match).join('')||'<div class="empty">Sin partidos.</div>'}</section><section class="card"><h3>Últimos 10</h3>${recent().slice(0,10).map(match).join('')||'<div class="empty">Sin resultados.</div>'}</section></div>`}
function render(){const r=mount(),real=new Map(S.teams.map(x=>[N(x.name),x])),ts=T.map(name=>({...real.get(N(name)),name,key:N(name)})).map(x=>({...x,...(S.table.find(t=>t.key===x.key)||{})})).sort((a,b)=>(a.rank??99)-(b.rank??99));r.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('on',b.dataset.tab===S.tab));const st=r.querySelector('#tv5state');st.textContent=S.err.length?'Datos parciales':S.loading?'Cargando':'Datos reales';st.classList.toggle('warn',S.err.length>0);r.querySelector('#tv5err').innerHTML=S.err.length?`<div class="note">${S.err.map(E).join(' · ')}</div>`:'';r.querySelector('#tv5view').innerHTML=S.tab==='resumen'?summary(ts):S.tab==='equipos'?teamsView(ts):S.tab==='jugadores'?playersView():S.tab==='lesiones'?injuriesView():calendarView();const se=r.querySelector('#tv5s');if(se)se.oninput=()=>{const q=N(se.value);r.querySelectorAll('#tv5view tbody tr').forEach(x=>x.style.display=!q||N(x.textContent).includes(q)?'':'none')};const ps=r.querySelector('#tv5ps');if(ps)ps.oninput=()=>{const q=N(ps.value);r.querySelector('#tv5pt').innerHTML=playersRows(S.players.filter(x=>N(x.name).includes(q)||N(x.team).includes(q)).slice(0,100))}}
async function seed(){try{const d=await get('/official-fixtures-seed-2026-27.json');const x=fixtures({fixtures:d.fixtures});if(x.length){S.fixtures=x;S.source=d.source||'LALIGA oficial';return true}}catch{}return false}
async function load(){S.loading=true;render();const out=await Promise.allSettled([get('/api/data/teams'),get('/api/data/standings'),get('/api/data/injuries'),get('/api/fixtures'),get('/api/data/players?page=1')]);const [a,b,c,d,e]=out;S.teams=a.status==='fulfilled'?teams(a.value):[];S.table=b.status==='fulfilled'?table(b.value):[];S.injuries=c.status==='fulfilled'?injuries(c.value):[];S.fixtures=d.status==='fulfilled'?fixtures(d.value):[];S.players=e.status==='fulfilled'?players(e.value):[];S.err=out.flatMap(x=>x.status==='rejected'?[String(x.reason?.message||x.reason||'Error')]:[]);if(!S.fixtures.length)await seed();S.loading=false;render()}
function boot(){mount();load();setInterval(load,30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();