import assert from 'node:assert/strict';
import fs from 'node:fs';
const ui=fs.readFileSync('./teams-data-v4.js','utf8');
const config=fs.readFileSync('./config.mjs','utf8');
const connection=fs.readFileSync('./connection-client.js','utf8');
const host=fs.readFileSync('./brain-host-v27.mjs','utf8');
const sw=fs.readFileSync('./sw.js','utf8');
const seed=fs.readFileSync('./official-fixtures-seed-2026-27.json','utf8');
const teams=['Athletic Club','Atlético de Madrid','CA Osasuna','Celta','Deportivo Alavés','Elche CF','FC Barcelona','Getafe CF','Levante UD','Málaga CF','R. Racing Club','Rayo Vallecano','RC Deportivo','RCD Espanyol de Barcelona','Real Betis','Real Madrid','Real Sociedad','Sevilla FC','Valencia CF','Villarreal CF'];
assert.equal((ui.match(/\['[^']+','[^']+'\]/g)||[]).length>=20,true);
for(const team of teams)assert.ok(ui.includes(team),`missing ${team}`);
assert.ok(config.includes("'/teams-data-v4.js'"));
assert.ok(!config.includes("'/teams-data-v2.js'"));
assert.ok(!config.includes("'/teams-data-v3.js'"));
assert.ok(!config.includes("'/teams-futbolfantasy-v1.js'"));
assert.ok(connection.includes("loadInline('/teams-data-v4.js','4')"));
assert.ok(!connection.includes("loadInline('/teams-futbolfantasy-v1.js','1')"));
assert.ok(host.includes("'/teams-data-v4.js':['teams-data-v4.js'"));
assert.ok(sw.includes("'./teams-data-v4.js'"));
assert.ok(!sw.includes("'./teams-futbolfantasy-v1.js'"));
for(const endpoint of ['/api/data/teams','/api/data/players','/api/data/standings','/api/data/injuries','/api/fixtures'])assert.ok(ui.includes(endpoint),`missing ${endpoint}`);
for(const tab of ['resumen','equipos','jugadores','lesiones','calendario'])assert.ok(ui.includes(`data-tab=\"${tab}\"`),`missing ${tab}`);
for(const token of ['tab:\'resumen\'','homeScore','awayScore','merged','loadFixtureSeed','totalPages','Jugadores reales cargados','Próximos partidos','GF','GC','DG'])assert.ok(ui.includes(token),`missing ${token}`);
assert.ok(seed.includes('"season":"2026/27"'));
assert.ok(seed.includes('"source":"LALIGA oficial"'));
assert.ok(seed.includes('"currentMatchday":4'));
assert.ok(seed.includes('"matchday":4'));
assert.ok(!fs.existsSync('./teams-data-v2.js'));
assert.ok(!fs.existsSync('./teams-data-v3.js'));
assert.ok(!fs.existsSync('./teams-futbolfantasy-v1.js'));
console.log('DATA CENTER UI v4: compact football-style views · real-data extraction · official fixture fallback · obsolete layers removed');
