import assert from 'node:assert/strict';
import fs from 'node:fs';

const agent = fs.readFileSync('./scripts/self-heal-agent.mjs', 'utf8');
const policy = JSON.parse(fs.readFileSync('./.github/self-healing/policy.json', 'utf8'));
const workflow = fs.readFileSync('./.github/workflows/self-healing-ai.yml', 'utf8');
const memory = JSON.parse(fs.readFileSync('./.github/self-healing/memory.json', 'utf8'));

assert.ok(agent.includes('/v1/responses'));
assert.ok(agent.includes('gpt-5.6-luna'));
assert.ok(agent.includes('git apply --check'));
assert.ok(agent.includes('npm'));
assert.ok(agent.includes("process.env.GITHUB_TOKEN"));
assert.ok(agent.includes('memory.repairs'));
assert.ok(agent.includes('memory.failures'));
assert.ok(agent.includes('SELF_HEAL_MAX_ATTEMPTS'));
assert.ok(agent.includes('PATCH_SECRET_PATTERN'));
assert.ok(agent.includes('PATCH_PATH_NOT_ALLOWED'));
assert.ok(agent.includes('PATCH_TOO_LARGE'));
assert.ok(agent.includes('SELF_HEAL_SUCCESS'));
assert.ok(agent.includes('SELF_HEAL_UNREPAIRED'));
assert.equal(policy.mode, 'safe-autonomous');
assert.equal(policy.requireTests, true);
assert.equal(policy.requireNoSecrets, true);
assert.equal(policy.readOnlyFantasyPolicy, true);
assert.ok(policy.maxChangedFiles <= 8);
assert.ok(policy.maxPatchLines <= 500);
assert.ok(workflow.includes('workflow_run:'));
assert.ok(workflow.includes('types: [completed]'));
assert.ok(workflow.includes('contents: write'));
assert.ok(workflow.includes('pull-requests: write'));
assert.ok(workflow.includes('OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}'));
assert.ok(workflow.includes('node scripts/self-heal-agent.mjs'));
assert.ok(workflow.includes('git push --force-with-lease'));
assert.ok(workflow.includes('gh pr create'));
assert.deepEqual(memory, { version: 1, updatedAt: null, repairs: [], failures: [] });
console.log('SELF-HEALING AI CONTRACT: 25/25 checks passed');
