import assert from 'node:assert/strict';
import { failureFingerprint, canAttempt, learnFailure, learnRepair, learnCorrection, recall } from './self-heal-memory-v2.mjs';

const base={version:'2.0.0',updatedAt:null,repairs:[],failures:[],corrections:[]};
const logsA='AssertionError: calendar failed at 2026-08-29T16:00:00Z run_id 123';
const logsB='AssertionError: calendar failed at 2026-08-29T17:00:00Z run_id 999';
const fpA=failureFingerprint('Project tests',logsA),fpB=failureFingerprint('Project tests',logsB);
assert.equal(fpA,fpB);
let memory=learnFailure(base,{workflow:'Project tests',signature:logsA,outcome:'unrepaired',at:new Date().toISOString()});
assert.equal(memory.version,'2.0.0');
assert.equal(canAttempt(memory,fpA,{maxAttempts24h:2}).ok,true);
memory=learnFailure(memory,{workflow:'Project tests',signature:logsA,outcome:'unrepaired',at:new Date().toISOString()});
assert.equal(canAttempt(memory,fpA,{maxAttempts24h:2}).reason,'COOLDOWN');
memory=learnRepair(memory,{workflow:'Project tests',signature:logsA,outcome:'tests-passed',fixedAt:new Date().toISOString()});
assert.equal(canAttempt(memory,fpA,{maxAttempts24h:9}).reason,'ALREADY_FIXED');
memory=learnCorrection(memory,{id:'calendar-merge-information-loss',area:'calendar',rootCause:'primary source dropped valid secondary live data',correction:'fill missing scores and promote non-downgrading status'});
assert.equal(memory.corrections.length,1);
assert.equal(recall(memory,'Project tests',logsB).fingerprint,fpA);
assert.equal(recall(memory,'calendar',logsB).corrections[0].id,'calendar-merge-information-loss');
console.log('SELF-HEAL MEMORY v2: 7/7 assertions passed');
